---
- name: Install and configure Elasticsearch on Ubuntu 22.04
  hosts: elasticsearch
  become: yes
  become_method: sudo  # Explicitly set sudo
  become_user: root  # Run as root
  
  pre_tasks:
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"
  
  roles:
    - elasticsearch_install
    - elasticsearch_configure
    - elasticsearch_service
    - elasticsearch_heapsize

  handlers:
    - name: Restart Elasticsearch
      systemd:
        name: elasticsearch
        state: restarted
