---
- name: Install necessary apt packages
  apt:
    name:
      - apt-transport-https
      - openjdk-11-jre
      - curl
    state: present
    update_cache: yes

- name: Download and install Elasticsearch
  shell: |
    curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo tee /etc/apt/trusted.gpg.d/elastic.asc
    echo "deb https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-8.x.list
    sudo apt update && sudo apt install elasticsearch -y
